import Head from 'next/head'
import Image from 'next/image'
import axios from 'axios'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import Banner from '@/components/Banner'
import Smallcard from '@/components/Smallcard'
import Bigcards from '@/components/Bigcards'
import LargeCard from '@/components/LargeCard'
import Footer from '@/components/Footer'



export default function Home({exploreData,BigCardsData}) {

    
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header/>
      <Banner/>

    <main className='max-w-7xl mx-auto px-8 sm:px-16'>
      <section className='pt-6'>
        <h2 className='text-4xl font-semibold pb-5'>Explore nearby</h2>

       <div className='grid sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4'>
       {exploreData?.map(({img,distance,location})=>(

                  <Smallcard
                   key={img}
                     img={img}
                     distance={distance}
                   location={location}

                             />

               ))}
       </div>
        
      </section>
      <section>
        <h2 className='text-4xl font-semibold py-8'>Live anywhere</h2>
       <div className='flex space-x-4 overflow-scroll scrollbar-hide ml-3 p-3'>
        {BigCardsData?.map(({img,title})=>(
          <Bigcards  key={img} img={img} title={title} />
        ))}
        </div>
      </section>
      <LargeCard 

      img="https://links.papareact.com/4cj"
      title='The Greatest Outdoors'
      description="Wishlists curated by Airbnb"
      buttonText="Get Inspired"
      
      
      />
    </main>
    <Footer/>
    </>

  )
}

export async function getStaticProps() {

  const exploreData=await fetch('https://www.jsonkeeper.com/b/4G1G').then((res)=>res.json())
  const BigCardsData=await fetch("https://www.jsonkeeper.com/b/VHHT").then((res)=>res.json())
  
  return{
    props:{
      exploreData,
      BigCardsData
    }
  }


}





